# Generated by Django 5.2.6 on 2025-09-30 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_notification_id_alter_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6fad98d-6597-427f-a639-05f7813edfb8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c219b6b4-f6f0-4005-b3af-0d93ed08c2bd'), editable=False, primary_key=True, serialize=False)),
                ('old_message', models.TextField()),
                ('edited_at', models.DateField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.message')),
            ],
        ),
    ]
