# Generated by Django 5.2.6 on 2025-10-02 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_edited_alter_notification_id_messagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94f4bf1c-32c4-4067-b6e8-779ff0192ff0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8215da6e-90a3-4a3b-a9c8-73fc38aded9e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
