# Generated by Django 5.2.6 on 2025-10-02 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_messagehistory_id_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7d6066ec-5b4c-4977-8b57-06f12f799b19'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d4f9683-dc87-40d3-b5e4-a1db0467d86c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
