# Generated by Django 5.2.6 on 2025-10-02 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_messagehistory_id_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('405e2d3e-741a-4131-9594-0e34b3b45254'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdf2fe22-fdf2-4294-a211-a1dea7c29eb6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
