# Generated by Django 5.2.6 on 2025-10-02 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_messagehistory_id_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2a544c7-3753-4660-8363-a7bdb104663a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3e974cd-fcf7-407b-8f6a-155cdaf40f55'), editable=False, primary_key=True, serialize=False),
        ),
    ]
