# Generated by Django 5.2.6 on 2025-10-02 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_messagehistory_id_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0f1cc4cc-b797-4df3-a8bd-d1a9bc4980d8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10b6e163-a9f9-401e-8063-b15a29d07fb4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
