# Generated by Django 5.2.6 on 2025-10-02 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_alter_messagehistory_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9999a0cc-c659-47a2-9538-25c87eecddcb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93090e8f-fb6f-47cb-b121-7933871d5ed5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
