services:
  web:
    build: .
    command: >
      sh -c "sleep 10 &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput --clear &&
          python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: mysql:9.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_info:/var/lib/mysql
volumes:
  db_info:
