pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = 'github-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/GodwinCyber/alx-backend-python.git',
                    credentialsId: "${GITHUB_CREDENTIALS}"
            }
        }

        stage('Install Python') {
            steps {
                sh '''
                if ! command -v python3 &> /dev/null
                then
                    echo "Python3 not found. Installing..."
                    apt-get update && apt-get install -y python3 python3-venv python3-pip
                else
                    echo "Python3 is already installed."
                fi
                '''
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished successfully.'
        }
    }
}
