pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = 'github-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', 
                    url: 'https://github.com/GodwinCyber/alx-backend-python.git', 
                    credentialsId: "${GITHUB_CREDENTIALS}"
            }
        }

        stage('Setup Virtualenv & Install Dependencies') {
            steps {
                sh '''
                # Create a new virtual environment
                python3 -m venv venv

                # Activate it and install dependencies
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
