apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-web # Initaiily routes traffic to the BLUE deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP



